### Splunk Input Configuration
### Location: C:\Program Files\Splunk\etc\system\local\inputs.conf

# Windows Application Logs
[WinEventLog://Application]
index = endpoint
sourcetype = WinEventLog
disabled = 0

# Windows System Logs
[WinEventLog://System]
index = endpoint
sourcetype = WinEventLog
disabled = 0

# Windows Security Logs
[WinEventLog://Security]
index = security
sourcetype = WinEventLog
disabled = 0

# Sysmon Operational Logs
[WinEventLog://Microsoft-Windows-Sysmon/Operational]
index = endpoint
sourcetype = XmlWinEventLog
disabled = 0

# Windows PowerShell Logs
[WinEventLog://Windows PowerShell]
index = endpoint
sourcetype = WinEventLog
disabled = 0

# Setup Logs
[WinEventLog://Setup]
index = endpoint
sourcetype = WinEventLog
disabled = 0

# Forwarded Events
[WinEventLog://ForwardedEvents]
index = endpoint
sourcetype = WinEventLog
disabled = 0

# Internet Explorer Logs
[WinEventLog://Internet Explorer]
index = endpoint
sourcetype = WinEventLog
disabled = 0

# PowerShell Operation Logs
[WinEventLog://Microsoft-Windows-PowerShell/Operational]
index = endpoint
sourcetype = XmlWinEventLog
disabled = 0

# Perflogs (Performance Logs)
[WinEventLog://PerfLogs]
index = endpoint
sourcetype = WinEventLog
disabled = 0
